# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=5, verbose_name='名称')),
                ('percent', models.IntegerField(default=0, verbose_name='占比')),
                ('count', models.IntegerField(default=0, verbose_name='报警数量')),
            ],
        ),
    ]
