# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-26 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0002_typecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecount',
            name='biz_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='业务id'),
        ),
        migrations.AddField(
            model_name='typecount',
            name='biz_name',
            field=models.CharField(default='', max_length=20, verbose_name='业务名称'),
        ),
    ]
