# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-26 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0003_auto_20190726_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecount',
            name='percent',
            field=models.CharField(default='0%', max_length=5, verbose_name='占比'),
        ),
    ]
