# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0004_auto_20190726_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='属性名称')),
                ('value', models.CharField(max_length=20, verbose_name='属性值')),
            ],
        ),
        migrations.AlterField(
            model_name='typecount',
            name='percent',
            field=models.CharField(default=0, max_length=5, verbose_name='占比'),
        ),
    ]
