# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-26 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0005_auto_20190726_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='remark',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='备注'),
        ),
    ]
