# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-26 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0006_option_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='BizCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.CharField(default=0, max_length=5, verbose_name='占比')),
                ('count', models.IntegerField(default=0, verbose_name='报警数量')),
                ('biz_id', models.IntegerField(blank=True, null=True, verbose_name='业务id')),
                ('biz_name', models.CharField(default='', max_length=20, verbose_name='业务名称')),
            ],
        ),
    ]
