# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-31 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0010_disk_mem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='mem',
            name='time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
