# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-29 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0012_visualconf_visualparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualconf',
            name='biz_id',
            field=models.IntegerField(null=True, verbose_name='业务id'),
        ),
    ]
