# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-29 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0013_visualconf_biz_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualparameter',
            name='api',
        ),
        migrations.AddField(
            model_name='visualconf',
            name='api',
            field=models.CharField(default=0, max_length=200, verbose_name='接口地址'),
            preserve_default=False,
        ),
    ]
