# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0014_auto_20190829_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualconf',
            name='biz_name',
            field=models.CharField(max_length=20, null=True, verbose_name='业务名称'),
        ),
    ]
