# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-30 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0015_auto_20190829_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualparameter',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='visualparameter',
            name='visualConf',
        ),
        migrations.AddField(
            model_name='visualconf',
            name='kwargs',
            field=models.CharField(max_length=200, null=True, verbose_name='参数'),
        ),
    ]
